In [ ]:
import os
from google.colab import drive

In [ ]:
import pandas as pd
import numpy as np

## csv파일 불러오기

In [ ]:
movies = pd.read_csv("movies.csv")
movies

movieId                                      title  \
0           1                           Toy Story (1995)   
1           2                             Jumanji (1995)   
2           3                    Grumpier Old Men (1995)   
3           4                   Waiting to Exhale (1995)   
4           5         Father of the Bride Part II (1995)   
...       ...                                        ...   
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                                           genres  
0     Adventure|Animation|Children|Comedy|Fantasy  
1                      Adventure|Children|Fantasy  
2                                  Comedy|Romance  
3                            Comedy|Drama|Romance  
4                                          Comedy  
...                                           ...  
9737              Action|Animation|Comedy|Fantasy  
9738                     Animation|Comedy|Fantasy  
9739                                        Drama  
9740                             Action|Animation  
9741                                       Comedy  

[9742 rows x 3 columns]

In [ ]:
tags = pd.read_csv("tags.csv")
tags

userId  movieId               tag   timestamp
0          2    60756             funny  1445714994
1          2    60756   Highly quotable  1445714996
2          2    60756      will ferrell  1445714992
3          2    89774      Boxing story  1445715207
4          2    89774               MMA  1445715200
...      ...      ...               ...         ...
3678     606     7382         for katie  1171234019
3679     606     7936           austere  1173392334
3680     610     3265            gun fu  1493843984
3681     610     3265  heroic bloodshed  1493843978
3682     610   168248  Heroic Bloodshed  1493844270

[3683 rows x 4 columns]

In [ ]:
ratings = pd.read_csv("ratings.csv")
ratings

userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

## 중복체크

In [ ]:
len(movies)  # 무비 데이터 수

9742

In [ ]:
movies['movieId'].nunique()  # 무비 id 수

9742

In [ ]:
movies['title'].nunique()  # 무비 제목 != 무비 id 수

9737

5개의 영화가 겹치는 것을 확인

In [ ]:
movies[movies.duplicated('title')]

movieId                                   title  \
5601    26958                             Emma (1996)   
6932    64997                War of the Worlds (2005)   
9106   144606  Confessions of a Dangerous Mind (2002)   
9135   147002                             Eros (2004)   
9468   168358                         Saturn 3 (1980)   

                                   genres  
5601                              Romance  
6932                        Action|Sci-Fi  
9106  Comedy|Crime|Drama|Romance|Thriller  
9135                        Drama|Romance  
9468                      Sci-Fi|Thriller

In [ ]:
movies['title'].value_counts()[movies['title'].value_counts() > 1]

Emma (1996)                               2
War of the Worlds (2005)                  2
Confessions of a Dangerous Mind (2002)    2
Eros (2004)                               2
Saturn 3 (1980)                           2
Name: title, dtype: int64

위 5개의 영화가 1개씩 더 들어가 있는 것을 확인

## 중복값 처리

1) Emma 중복 제거


In [ ]:
movies[movies['title'] == 'Emma (1996)']

movieId        title                genres
650       838  Emma (1996)  Comedy|Drama|Romance
5601    26958  Emma (1996)               Romance

In [ ]:
#Emma Movie_Id / 26958 -> 838로 변경 / ratings

refined_ratings = ratings.copy()

print(refined_ratings[refined_ratings['movieId'] == 26958])

       userId  movieId  rating   timestamp
80596     509    26958     3.5  1436031753


In [ ]:
print(refined_ratings[refined_ratings['movieId'] == 838])

       userId  movieId  rating   timestamp
849         6      838     4.0   845555514
1332       12      838     5.0  1247264096
5096       33      838     5.0   939716327
8146       57      838     3.0   965797105
10504      68      838     3.5  1158535598
13223      84      838     5.0   857653794
15339     100      838     4.5  1100184279
15984     104      838     4.0  1049291806
17015     108      838     5.0  1042840302
17996     113      838     4.0   980051757
19982     132      838     2.0  1157923556
22744     156      838     3.0   939843105
29958     206      838     5.0   850763507
35990     246      838     4.0  1354126122
42217     288      838     3.0   978559679
52660     345      838     5.0  1342826728
56237     372      838     4.0   874414806
62617     414      838     3.0   961438642
72518     469      838     3.0   965425513
73277     474      838     3.0   974668977
76072     479      838     5.0  1039362753
78385     488      838     5.0  1112382382
78581     4

In [ ]:
refined_ratings.loc[refined_ratings['movieId'] == 26958, 'movieId'] = 838

print(refined_ratings[refined_ratings['movieId'] == 26958])

Empty DataFrame
Columns: [userId, movieId, rating, timestamp]
Index: []


In [ ]:
#moives <- Emma 중복 행 삭제
refined_movies = movies[movies['movieId'] != 26958]

refined_movies[refined_movies['title'] == 'Emma (1996)']

movieId        title                genres
650      838  Emma (1996)  Comedy|Drama|Romance

In [ ]:
#Emma Movie_Id / 26958 -> 838로 변경 / tags

refined_tags = tags.copy()

print(refined_ratings[refined_ratings['movieId'] == 26958])

# 원래 없어서 변경할 필요 X

Empty DataFrame
Columns: [userId, movieId, rating, timestamp]
Index: []


2) War of the Worlds 중복 제거


In [ ]:
#이미 refine된 DF가 있으므로 이어서 진행

refined_movies[refined_movies['title'] == 'War of the Worlds (2005)']

movieId                     title                            genres
5931    34048  War of the Worlds (2005)  Action|Adventure|Sci-Fi|Thriller
6932    64997  War of the Worlds (2005)                     Action|Sci-Fi

In [ ]:
#War of the Worlds Movie_Id / 64997 -> 34048로 변경 / ratings

print(refined_ratings[refined_ratings['movieId'] == 64997])

       userId  movieId  rating   timestamp
4747       28    64997     3.5  1234850075
11451      68    64997     2.5  1230497715


In [ ]:
print(refined_ratings[refined_ratings['movieId'] == 34048])

        userId  movieId  rating   timestamp
1009         7    34048     3.0  1121041015
3422        21    34048     3.5  1468113413
4590        28    34048     3.5  1234516420
11241       68    34048     2.0  1158532246
12349       76    34048     3.0  1439165897
12615       80    34048     4.0  1377308367
16570      105    34048     3.5  1446749836
19810      129    34048     3.5  1167376772
20990      139    34048     1.5  1453924481
21657      140    34048     3.0  1166645504
25499      177    34048     3.0  1435524709
27064      182    34048     2.0  1120879654
31949      219    34048     2.0  1194932220
32589      221    34048     2.5  1121365127
33504      226    34048     2.0  1121367045
33857      230    34048     4.5  1196305083
34409      232    34048     3.5  1218167705
35534      239    34048     3.5  1221147897
36821      249    34048     3.5  1355366539
40258      274    34048     2.5  1173041328
43087      288    34048     3.0  1147093480
43770      292    34048     4.0 

In [ ]:
refined_ratings.loc[refined_ratings['movieId'] == 64997, 'movieId'] = 34048

print(refined_ratings[refined_ratings['movieId'] == 64997])

Empty DataFrame
Columns: [userId, movieId, rating, timestamp]
Index: []


In [ ]:
#moives <- War of the Worlds 중복 행 삭제
refined_movies = refined_movies[refined_movies['movieId'] != 64997]

refined_movies[refined_movies['title'] == 'War of the Worlds (2005)']

movieId                     title                            genres
5931    34048  War of the Worlds (2005)  Action|Adventure|Sci-Fi|Thriller

In [ ]:
#War of the Worlds Movie_Id / 64997 -> 34048로 변경 / tags
#이미 refine된 DF가 있으므로 이어서 진행

print(refined_ratings[refined_ratings['movieId'] == 64997])

# 원래 없어서 변경할 필요 X

Empty DataFrame
Columns: [userId, movieId, rating, timestamp]
Index: []


3) Confessions of a Dangerous Mind 중복 제거

In [ ]:
refined_movies[refined_movies['title'] == 'Confessions of a Dangerous Mind (2002)']

movieId                                   title  \
4169     6003  Confessions of a Dangerous Mind (2002)   
9106   144606  Confessions of a Dangerous Mind (2002)   

                                   genres  
4169          Comedy|Crime|Drama|Thriller  
9106  Comedy|Crime|Drama|Romance|Thriller

In [ ]:
#Confessions of a Dangerous Mind Movie_Id / 144606 -> 6003으로 변경 / ratings

print(refined_ratings[refined_ratings['movieId'] == 6003])

       userId  movieId  rating   timestamp
17449     111     6003     4.0  1516468531
23053     156     6003     3.5  1106882187
26958     182     6003     3.0  1054780821
42984     288     6003     4.0  1066059244
54020     356     6003     4.5  1229139513
59953     387     6003     3.5  1208707060
64063     414     6003     3.5  1092414917
74530     474     6003     3.5  1087831997
76779     480     6003     3.5  1179161261
85111     552     6003     3.0  1112151145
89614     580     6003     3.5  1167860103
94099     599     6003     3.0  1498527101
95721     600     6003     3.0  1237759526
99357     608     6003     4.5  1117408056
99939     610     6003     4.0  1493847220


In [ ]:
print(refined_ratings[refined_ratings['movieId'] == 144606])

       userId  movieId  rating   timestamp
17819     111   144606     4.0  1517441257


In [ ]:
print(refined_ratings[refined_ratings['movieId'] == 6003])

       userId  movieId  rating   timestamp
17449     111     6003     4.0  1516468531
23053     156     6003     3.5  1106882187
26958     182     6003     3.0  1054780821
42984     288     6003     4.0  1066059244
54020     356     6003     4.5  1229139513
59953     387     6003     3.5  1208707060
64063     414     6003     3.5  1092414917
74530     474     6003     3.5  1087831997
76779     480     6003     3.5  1179161261
85111     552     6003     3.0  1112151145
89614     580     6003     3.5  1167860103
94099     599     6003     3.0  1498527101
95721     600     6003     3.0  1237759526
99357     608     6003     4.5  1117408056
99939     610     6003     4.0  1493847220


In [ ]:
refined_ratings.loc[refined_ratings['movieId'] == 144606, 'movieId'] = 6003

print(refined_ratings[refined_ratings['movieId'] == 144606])

Empty DataFrame
Columns: [userId, movieId, rating, timestamp]
Index: []


In [ ]:
#moives <- Confessions of a Dangerous Mind 중복 행 삭제
refined_movies = refined_movies[refined_movies['movieId'] != 144606]

refined_movies[refined_movies['title'] == 'Confessions of a Dangerous Mind (2002)']

movieId                                   title  \
4169     6003  Confessions of a Dangerous Mind (2002)   

                           genres  
4169  Comedy|Crime|Drama|Thriller

In [ ]:
#Confessions of a Dangerous Mind Movie_Id / 144606 -> 6003로 변경 / tags

print(refined_ratings[refined_ratings['movieId'] == 144606])

# 원래 없어서 변경할 필요 X

Empty DataFrame
Columns: [userId, movieId, rating, timestamp]
Index: []


4) Eros 중복 제거

In [ ]:
refined_movies[refined_movies['title'] == 'Eros (2004)']

movieId        title         genres
5854    32600  Eros (2004)          Drama
9135   147002  Eros (2004)  Drama|Romance

In [ ]:
#Eros Movie_Id / 147002 -> 32600으로 변경 / ratings

print(refined_ratings[refined_ratings['movieId'] == 32600])

       userId  movieId  rating   timestamp
98357     606    32600     3.5  1171410642


In [ ]:
print(refined_ratings[refined_ratings['movieId'] == 147002])

       userId  movieId  rating   timestamp
49832     318   147002     4.0  1502207152


In [ ]:
refined_ratings.loc[refined_ratings['movieId'] == 147002, 'movieId'] = 32600

print(refined_ratings[refined_ratings['movieId'] == 147002])

Empty DataFrame
Columns: [userId, movieId, rating, timestamp]
Index: []


In [ ]:
#moives <- Eros 중복 행 삭제
refined_movies = refined_movies[refined_movies['movieId'] != 147002]

refined_movies[refined_movies['title'] == 'Eros (2004)']

movieId        title genres
5854    32600  Eros (2004)  Drama

In [ ]:
#Eros Movie_Id / 147002 -> 32600로 변경 / tags

print(refined_ratings[refined_ratings['movieId'] == 147002])

# 원래 없어서 변경할 필요 X

Empty DataFrame
Columns: [userId, movieId, rating, timestamp]
Index: []


5) Saturn 3 중복 제거

In [ ]:
refined_movies[refined_movies['title'] == 'Saturn 3 (1980)']

movieId            title                     genres
2141     2851  Saturn 3 (1980)  Adventure|Sci-Fi|Thriller
9468   168358  Saturn 3 (1980)            Sci-Fi|Thriller

In [ ]:
#Saturn 3 Movie_Id / 168358 -> 2851으로 변경 / ratings

print(refined_ratings[refined_ratings['movieId'] == 2851])

       userId  movieId  rating   timestamp
282         3     2851     5.0  1306463925
31391     217     2851     3.0   955942393
42665     288     2851     2.0  1020369199
72810     469     2851     3.0   965335989


In [ ]:
print(refined_ratings[refined_ratings['movieId'] == 168358])

       userId  movieId  rating   timestamp
81458     514   168358     2.5  1533945970


In [ ]:
refined_ratings.loc[refined_ratings['movieId'] == 168358, 'movieId'] = 2851

print(refined_ratings[refined_ratings['movieId'] == 168358])

Empty DataFrame
Columns: [userId, movieId, rating, timestamp]
Index: []


In [ ]:
#moives <- Saturn 3 중복 행 삭제
refined_movies = refined_movies[refined_movies['movieId'] != 168358]

refined_movies[refined_movies['title'] == 'Saturn 3 (1980)']

movieId            title                     genres
2141     2851  Saturn 3 (1980)  Adventure|Sci-Fi|Thriller

In [ ]:
#Saturn 3 Movie_Id / 168358 -> 2851로 변경 / tags

print(refined_ratings[refined_ratings['movieId'] == 168358])

# 원래 없어서 변경할 필요 X

Empty DataFrame
Columns: [userId, movieId, rating, timestamp]
Index: []


In [ ]:
#9742 -> 9737로 중복 5개 제거 확인
refined_movies

movieId                                      title  \
0           1                           Toy Story (1995)   
1           2                             Jumanji (1995)   
2           3                    Grumpier Old Men (1995)   
3           4                   Waiting to Exhale (1995)   
4           5         Father of the Bride Part II (1995)   
...       ...                                        ...   
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                                           genres  
0     Adventure|Animation|Children|Comedy|Fantasy  
1                      Adventure|Children|Fantasy  
2                                  Comedy|Romance  
3                            Comedy|Drama|Romance  
4                                          Comedy  
...                                           ...  
9737              Action|Animation|Comedy|Fantasy  
9738                     Animation|Comedy|Fantasy  
9739                                        Drama  
9740                             Action|Animation  
9741                                       Comedy  

[9737 rows x 3 columns]

In [ ]:
len(refined_movies)

9737

In [ ]:
refined_movies['movieId'].nunique()

9737

In [ ]:
refined_movies['title'].nunique()

9737

##장르 없는 영화 처리

In [ ]:
no_genre_cond = refined_movies['genres'].str.contains(' ')
refined_movies[no_genre_cond]

movieId                                              title  \
8517   114335                                  La cravate (1957)   
8684   122888                                     Ben-hur (2016)   
8687   122896  Pirates of the Caribbean: Dead Men Tell No Tal...   
8782   129250                                  Superfast! (2015)   
8836   132084                                Let It Be Me (1995)   
8902   134861               Trevor Noah: African American (2013)   
9033   141131                                   Guardians (2016)   
9053   141866                                  Green Room (2015)   
9070   142456                     The Brand New Testament (2015)   
9091   143410                                         Hyena Road   
9138   147250  The Adventures of Sherlock Holmes and Doctor W...   
9178   149330                          A Cosmic Christmas (1977)   
9217   152037                                 Grease Live (2016)   
9248   155589                             Noin 7 veljestä (1968)   
9259   156605                                           Paterson   
9307   159161                        Ali Wong: Baby Cobra (2016)   
9316   159779                   A Midsummer Night's Dream (2016)   
9348   161008                         The Forbidden Dance (1990)   
9413   165489                              Ethel & Ernest (2016)   
9426   166024                                    Whiplash (2013)   
9448   167570                                             The OA   
9478   169034                                    Lemonade (2016)   
9514   171495                                             Cosmos   
9515   171631                            Maria Bamford: Old Baby   
9518   171749                  Death Note: Desu nôto (2006–2007)   
9525   171891                                  Generation Iron 2   
9534   172497                  T2 3-D: Battle Across Time (1996)   
9541   172591            The Godfather Trilogy: 1972-1990 (1992)   
9562   173535  The Adventures of Sherlock Holmes and Doctor W...   
9573   174403                        The Putin Interviews (2017)   
9611   176601                                       Black Mirror   
9661   181413  Too Funny to Fail: The Life and Death of The D...   
9663   181719  Serving in Silence: The Margarethe Cammermeyer...   
9669   182727                     A Christmas Story Live! (2017)   

                  genres  
8517  (no genres listed)  
8684  (no genres listed)  
8687  (no genres listed)  
8782  (no genres listed)  
8836  (no genres listed)  
8902  (no genres listed)  
9033  (no genres listed)  
9053  (no genres listed)  
9070  (no genres listed)  
9091  (no genres listed)  
9138  (no genres listed)  
9178  (no genres listed)  
9217  (no genres listed)  
9248  (no genres listed)  
9259  (no genres listed)  
9307  (no genres listed)  
9316  (no genres listed)  
9348  (no genres listed)  
9413  (no genres listed)  
9426  (no genres listed)  
9448  (no genres listed)  
9478  (no genres listed)  
9514  (no genres listed)  
9515  (no genres listed)  
9518  (no genres listed)  
9525  (no genres listed)  
9534  (no genres listed)  
9541  (no genres listed)  
9562  (no genres listed)  
9573  (no genres listed)  
9611  (no genres listed)  
9661  (no genres listed)  
9663  (no genres listed)  
9669  (no genres listed)

In [ ]:
len(refined_movies[no_genre_cond])

34

In [ ]:
len(refined_movies[~no_genre_cond])

9703

tags.csv 를 활용하여 장르가 없는 영화의 장르를 최대한 채운다.

In [ ]:
no_genre_movieId = refined_movies.loc[no_genre_cond, 'movieId'].tolist()
len(no_genre_movieId)

34

In [ ]:
no_genre_movieId

[114335,
 122888,
 122896,
 129250,
 132084,
 134861,
 141131,
 141866,
 142456,
 143410,
 147250,
 149330,
 152037,
 155589,
 156605,
 159161,
 159779,
 161008,
 165489,
 166024,
 167570,
 169034,
 171495,
 171631,
 171749,
 171891,
 172497,
 172591,
 173535,
 174403,
 176601,
 181413,
 181719,
 182727]

In [ ]:
ratings_ids = set(no_genre_movieId) & set(refined_ratings['movieId'])
ratings_movies = refined_ratings[refined_ratings['movieId'].isin(ratings_ids)]

print("장르가 없는 영화중 평가가 있는 영화:")
ratings_movies

장르가 없는 영화중 평가가 있는 영화:


userId  movieId  rating   timestamp
3624       21   122896     4.0  1452052163
7353       50   114335     3.0  1522446443
7408       50   174403     2.5  1527542476
9101       62   122896     3.5  1523047955
9141       62   172591     5.0  1525637301
9147       62   176601     5.0  1525795252
14028      89   155589     3.0  1520409520
16886     105   147250     5.0  1526207354
16913     105   171749     5.0  1526207365
16925     105   173535     4.5  1526206993
17780     111   122896     3.5  1516152736
17804     111   134861     2.5  1516154900
17837     111   159161     4.5  1517441228
17879     111   171631     1.0  1517440909
17881     111   171891     3.5  1517440199
19527     125   142456     4.5  1474295630
27246     184   181413     4.5  1537109726
30171     210   159779     4.0  1530467762
30471     212   122896     3.5  1528479617
36355     248   122896     4.0  1534592058
37495     252   122896     3.0  1498284070
44460     296   169034     4.5  1532994043
49825     318   142456     3.5  1501360248
49851     318   171495     5.0  1516826406
58077     380   172497     4.0  1494803341
64959     414   166024     4.5  1522624338
64964     414   167570     4.0  1511535836
70344     448   129250     0.5  1447868930
70432     448   143410     2.0  1474224802
81449     514   149330     4.0  1535944005
81466     514   182727     2.0  1536381035
81924     517   152037     1.0  1487958429
81929     517   165489     2.5  1487958674
83106     525   152037     3.0  1476478508
86573     560   141866     4.0  1469653431
88075     567   122888     0.5  1525289924
88111     567   141866     3.0  1525286842
88136     567   156605     4.5  1525283448
90221     586   122896     5.0  1529899587
92128     596   141131     2.5  1535712067
92154     596   181719     3.5  1535832847
95014     599   132084     2.5  1519142705
95034     599   141866     3.0  1498528489
95054     599   161008     2.5  1519100249
95078     599   171495     4.0  1519116912
95957     601   166024     5.0  1521467682
95961     601   172591     4.5  1521467819

In [ ]:
movie_id_counts = ratings_movies['movieId'].value_counts()
movie_id_counts

122896    7
141866    3
142456    2
152037    2
166024    2
171495    2
172591    2
147250    1
171749    1
132084    1
181719    1
141131    1
156605    1
122888    1
174403    1
165489    1
182727    1
149330    1
143410    1
129250    1
167570    1
176601    1
172497    1
114335    1
169034    1
159779    1
181413    1
155589    1
171891    1
171631    1
159161    1
134861    1
173535    1
161008    1
Name: movieId, dtype: int64

movieId = 122896은 5명 이상이 시청했으므로 장르 추측하기 유용하다고 판단

In [ ]:
#movieId=122896을 본 사용자 추출

ratings_movies[ratings_movies['movieId'] == 122896]

userId  movieId  rating   timestamp
3624       21   122896     4.0  1452052163
9101       62   122896     3.5  1523047955
17780     111   122896     3.5  1516152736
30471     212   122896     3.5  1528479617
36355     248   122896     4.0  1534592058
37495     252   122896     3.0  1498284070
90221     586   122896     5.0  1529899587

In [ ]:
ratings_movies[ratings_movies['userId'] == 586]

userId  movieId  rating   timestamp
90221     586   122896     5.0  1529899587

위의 7명을 전부 대조 해본 결과 추측하기 어려움(대부분이 122896 한 편만 봄)

In [ ]:
tags_ids = set(no_genre_movieId) & set(refined_tags['movieId'])
tags_movies = refined_tags[refined_tags['movieId'].isin(tags_ids)]

print("장르가 없는 영화중 tag가 있는 영화:")
print(tags_movies)

장르가 없는 영화중 tag가 있는 영화:
      userId  movieId          tag   timestamp
3279     567   156605       quirky  1525283453
3280     567   156605        sweet  1525283455
3281     567   156605  understated  1525283456


moiveId = 156605가 장르가 없는 영화 중 tag가 있는 영화로 확인

tag의 quirky, sweet, understated를 이용하여 장르 추측

tag에 quirky가 있는 movie

In [ ]:
refined_tags[refined_tags['tag'].str.contains('quirky', case=False)]

userId  movieId              tag   timestamp
61        62     2124           quirky  1525636846
125       62    27706           quirky  1526248553
714      424      223           quirky  1457844073
2740     477    69757           quirky  1279956145
2888     567      101           quirky  1525287214
2900     567      750           Quirky  1525287729
2927     567     1916           quirky  1525282930
3020     567     4878           quirky  1525282588
3028     567     5673           quirky  1525282629
3083     567     7361           quirky  1525282687
3084     567     7361  quirky romantic  1525282715
3107     567    30810           quirky  1525284031
3153     567    71899           quirky  1525283048
3169     567    94959           quirky  1525286360
3186     567   104875           quirky  1525285913
3205     567   108932           quirky  1525283678
3215     567   112421           quirky  1525283419
3244     567   122916           quirky  1525285291
3279     567   156605           quirky  1525283453
3376     599      293           quirky  1498456135
3513     599      296           quirky  1498456364
3617     599     1732           quirky  1498456263
3659     599     2959           quirky  1498456918

In [ ]:
quirky_list = refined_tags[refined_tags['tag'].str.contains('quirky', case=False)]['movieId'].values.tolist()
#1566505은 해당 영화이므로 제거
#7361은 quirky romantic 이므로 제거
quirky_list.remove(156605)
quirky_list.remove(7361)

quirky_list

[2124,
 27706,
 223,
 69757,
 101,
 750,
 1916,
 4878,
 5673,
 7361,
 30810,
 71899,
 94959,
 104875,
 108932,
 112421,
 122916,
 293,
 296,
 1732,
 2959]

In [ ]:
len(quirky_list)

21

In [ ]:
quirky_filtered_movies = refined_movies[refined_movies['movieId'].isin(quirky_list)]

quirky_filtered_movies

movieId                                              title  \
89        101                               Bottle Rocket (1996)   
190       223                                      Clerks (1994)   
254       293  Léon: The Professional (a.k.a. The Professiona...   
257       296                                Pulp Fiction (1994)   
602       750  Dr. Strangelove or: How I Learned to Stop Worr...   
1298     1732                           Big Lebowski, The (1998)   
1397     1916             Buffalo '66 (a.k.a. Buffalo 66) (1998)   
1585     2124                          Addams Family, The (1991)   
2226     2959                                  Fight Club (1999)   
3562     4878                                Donnie Darko (2001)   
4015     5673                            Punch-Drunk Love (2002)   
4909     7361       Eternal Sunshine of the Spotless Mind (2004)   
5680    27706  Lemony Snicket's A Series of Unfortunate Event...   
5737    30810         Life Aquatic with Steve Zissou, The (2004)   
7075    69757                        (500) Days of Summer (2009)   
7166    71899                                Mary and Max (2009)   
7894    94959                            Moonrise Kingdom (2012)   
8254   104875                 History of Future Folk, The (2012)   
8357   108932                              The Lego Movie (2014)   
8459   112421                                       Frank (2014)   
8694   122916                              Thor: Ragnarok (2017)   

                                                 genres  
89                       Adventure|Comedy|Crime|Romance  
190                                              Comedy  
254                         Action|Crime|Drama|Thriller  
257                         Comedy|Crime|Drama|Thriller  
602                                          Comedy|War  
1298                                       Comedy|Crime  
1397                                      Drama|Romance  
1585                            Children|Comedy|Fantasy  
2226                        Action|Crime|Drama|Thriller  
3562                      Drama|Mystery|Sci-Fi|Thriller  
4015                               Comedy|Drama|Romance  
4909                               Drama|Romance|Sci-Fi  
5680                  Adventure|Children|Comedy|Fantasy  
5737                           Adventure|Comedy|Fantasy  
7075                               Comedy|Drama|Romance  
7166                             Animation|Comedy|Drama  
7894                               Comedy|Drama|Romance  
8254                    Adventure|Comedy|Musical|Sci-Fi  
8357  Action|Adventure|Animation|Children|Comedy|Fan...  
8459                               Comedy|Drama|Mystery  
8694                            Action|Adventure|Sci-Fi

In [ ]:
# genres 열의 값을 "|"로 나누어 리스트로 변환
quirky_genres_list = quirky_filtered_movies['genres'].str.split('|').tolist()

# 리스트를 flat 하게 만들기
flat_genres_list = [quirky_genre for sublist in quirky_genres_list for quirky_genre in sublist]

# 각 장르의 개수 세기
from collections import Counter
genre_counts = Counter(flat_genres_list)

tag_genre_list = []

# 결과 출력
for quirky_genre, quirky_count in genre_counts.items():
    print(f"{quirky_genre}   {quirky_count}")
    tag_genre_list.append([quirky_genre, quirky_count])

Adventure   6
Comedy   15
Crime   5
Romance   6
Action   4
Drama   11
Thriller   4
War   1
Children   3
Fantasy   4
Mystery   2
Sci-Fi   4
Animation   2
Musical   1


In [ ]:
tag_genre_list

[['Adventure', 6],
 ['Comedy', 15],
 ['Crime', 5],
 ['Romance', 6],
 ['Action', 4],
 ['Drama', 11],
 ['Thriller', 4],
 ['War', 1],
 ['Children', 3],
 ['Fantasy', 4],
 ['Mystery', 2],
 ['Sci-Fi', 4],
 ['Animation', 2],
 ['Musical', 1]]

tag에 sweet가 있는 movie

In [ ]:
refined_tags[refined_tags['tag'].str.contains('sweet', case=False)]

userId  movieId          tag   timestamp
129       62    27808        sweet  1525554922
664      357     4370  Bittersweet  1348628628
2890     567      356  bittersweet  1525287545
2943     567     2324  bittersweet  1525285789
2987     567     4144  bittersweet  1525283563
3026     567     5673  bittersweet  1525282627
3069     567     7361  bittersweet  1525282677
3115     567    48394  bittersweet  1525286830
3140     567    68954  bittersweet  1525286758
3144     567    71899  bittersweet  1525283044
3155     567    71899        sweet  1525283052
3223     567   113705  bittersweet  1525286093
3280     567   156605        sweet  1525283455
3290     567   164909  Bittersweet  1525287656

In [ ]:
#156605를 제외하고, sweet가 들어간 영화는 2가지
sweet_list = [27808, 71899]

sweet_list

[27808, 71899]

In [ ]:
len(sweet_list)

2

In [ ]:
sweet_filtered_movies = refined_movies[refined_movies['movieId'].isin(sweet_list)]

sweet_filtered_movies

movieId                title                  genres
5705    27808     Spanglish (2004)    Comedy|Drama|Romance
7166    71899  Mary and Max (2009)  Animation|Comedy|Drama

In [ ]:
# genres 열의 값을 "|"로 나누어 리스트로 변환
sweet_genres_list = sweet_filtered_movies['genres'].str.split('|').tolist()

# 리스트를 flat 하게 만들기
flat_genres_list = [sweet_genre for sublist in sweet_genres_list for sweet_genre in sublist]

# 각 장르의 개수 세기
from collections import Counter
genre_counts = Counter(flat_genres_list)

# 결과 출력
for sweet_genre, sweet_count in genre_counts.items():
    print(f"{sweet_genre}   {sweet_count}")
    tag_genre_list.append([sweet_genre, sweet_count])

Comedy   2
Drama   2
Romance   1
Animation   1


In [ ]:
tag_genre_list

[['Adventure', 6],
 ['Comedy', 15],
 ['Crime', 5],
 ['Romance', 6],
 ['Action', 4],
 ['Drama', 11],
 ['Thriller', 4],
 ['War', 1],
 ['Children', 3],
 ['Fantasy', 4],
 ['Mystery', 2],
 ['Sci-Fi', 4],
 ['Animation', 2],
 ['Musical', 1],
 ['Comedy', 2],
 ['Drama', 2],
 ['Romance', 1],
 ['Animation', 1]]

tag에 understated가 있는 movie

In [ ]:
refined_tags[refined_tags['tag'].str.contains('understated', case=False)]

userId  movieId          tag   timestamp
3250     567   127298  understated  1525286256
3281     567   156605  understated  1525283456

In [ ]:
understated_list = refined_tags[refined_tags['tag'].str.contains('understated', case=False)]['movieId'].values.tolist()
#1566505은 해당 영화이므로 제거
understated_list.remove(156605)

understated_list

[127298]

In [ ]:
len(understated_list)

1

In [ ]:
understated_filtered_movies = refined_movies[refined_movies['movieId'].isin(understated_list)]

understated_filtered_movies

movieId                                              title        genres
8748   127298  A Pigeon Sat on a Branch Reflecting on Existen...  Comedy|Drama

In [ ]:
# genres 열의 값을 "|"로 나누어 리스트로 변환
understated_genres_list = understated_filtered_movies['genres'].str.split('|').tolist()

# 리스트를 flat 하게 만들기
flat_genres_list = [understated_genre for sublist in understated_genres_list for understated_genre in sublist]

# 각 장르의 개수 세기
from collections import Counter
genre_counts = Counter(flat_genres_list)

# 결과 출력
for understated_genre, understated_count in genre_counts.items():
    print(f"{understated_genre}   {understated_count}")
    tag_genre_list.append([understated_genre, understated_count])

Comedy   1
Drama   1


In [ ]:
tag_genre_list

[['Adventure', 6],
 ['Comedy', 15],
 ['Crime', 5],
 ['Romance', 6],
 ['Action', 4],
 ['Drama', 11],
 ['Thriller', 4],
 ['War', 1],
 ['Children', 3],
 ['Fantasy', 4],
 ['Mystery', 2],
 ['Sci-Fi', 4],
 ['Animation', 2],
 ['Musical', 1],
 ['Comedy', 2],
 ['Drama', 2],
 ['Romance', 1],
 ['Animation', 1],
 ['Comedy', 1],
 ['Drama', 1]]

tag에 따른 장르와 개수/비율 집계

전체 나온 영화의 개수는 21 + 2 + 1 = 24

(중복제거를 하지 않은 이유는 tag가 여러개 겹치는 항목은 추가 가중치를 부여하기 위함)

In [ ]:
len(quirky_list) + len(sweet_list) + len(understated_list)

24

In [ ]:
# 딕셔너리 초기화
genre_dict = {}

# 중복 항목 처리 및 값 더하기
for genre, count in tag_genre_list:
    if genre in genre_dict:
        genre_dict[genre] += count
    else:
        genre_dict[genre] = count

# 딕셔너리를 리스트로 변환
genre_data = [[genre, count] for genre, count in genre_dict.items()]

genre_data

[['Adventure', 6],
 ['Comedy', 18],
 ['Crime', 5],
 ['Romance', 7],
 ['Action', 4],
 ['Drama', 14],
 ['Thriller', 4],
 ['War', 1],
 ['Children', 3],
 ['Fantasy', 4],
 ['Mystery', 2],
 ['Sci-Fi', 4],
 ['Animation', 3],
 ['Musical', 1]]

In [ ]:
for item in genre_data:
    item[1] /= 24

genre_data

[['Adventure', 0.25],
 ['Comedy', 0.75],
 ['Crime', 0.20833333333333334],
 ['Romance', 0.2916666666666667],
 ['Action', 0.16666666666666666],
 ['Drama', 0.5833333333333334],
 ['Thriller', 0.16666666666666666],
 ['War', 0.041666666666666664],
 ['Children', 0.125],
 ['Fantasy', 0.16666666666666666],
 ['Mystery', 0.08333333333333333],
 ['Sci-Fi', 0.16666666666666666],
 ['Animation', 0.125],
 ['Musical', 0.041666666666666664]]

50% 이상 존재하는 것을 장르로 취급 = 'Comedy' , 'Drama'

따라서 movieId = 156605 의 장르는 'Comedy' , 'Drama'로 설정

In [ ]:
refined_movies[refined_movies['movieId'] == 156605]

movieId     title              genres
9259   156605  Paterson  (no genres listed)

In [ ]:
refined_movies.loc[refined_movies['movieId'] == 156605, 'genres'] = 'Comedy|Drama'

refined_movies[refined_movies['movieId'] == 156605]

movieId     title        genres
9259   156605  Paterson  Comedy|Drama

장르 없는 영화 제거

In [ ]:
no_genre_cond = refined_movies['genres'].str.contains(' ')
refined_movies[no_genre_cond]

movieId                                              title  \
8517   114335                                  La cravate (1957)   
8684   122888                                     Ben-hur (2016)   
8687   122896  Pirates of the Caribbean: Dead Men Tell No Tal...   
8782   129250                                  Superfast! (2015)   
8836   132084                                Let It Be Me (1995)   
8902   134861               Trevor Noah: African American (2013)   
9033   141131                                   Guardians (2016)   
9053   141866                                  Green Room (2015)   
9070   142456                     The Brand New Testament (2015)   
9091   143410                                         Hyena Road   
9138   147250  The Adventures of Sherlock Holmes and Doctor W...   
9178   149330                          A Cosmic Christmas (1977)   
9217   152037                                 Grease Live (2016)   
9248   155589                             Noin 7 veljestä (1968)   
9307   159161                        Ali Wong: Baby Cobra (2016)   
9316   159779                   A Midsummer Night's Dream (2016)   
9348   161008                         The Forbidden Dance (1990)   
9413   165489                              Ethel & Ernest (2016)   
9426   166024                                    Whiplash (2013)   
9448   167570                                             The OA   
9478   169034                                    Lemonade (2016)   
9514   171495                                             Cosmos   
9515   171631                            Maria Bamford: Old Baby   
9518   171749                  Death Note: Desu nôto (2006–2007)   
9525   171891                                  Generation Iron 2   
9534   172497                  T2 3-D: Battle Across Time (1996)   
9541   172591            The Godfather Trilogy: 1972-1990 (1992)   
9562   173535  The Adventures of Sherlock Holmes and Doctor W...   
9573   174403                        The Putin Interviews (2017)   
9611   176601                                       Black Mirror   
9661   181413  Too Funny to Fail: The Life and Death of The D...   
9663   181719  Serving in Silence: The Margarethe Cammermeyer...   
9669   182727                     A Christmas Story Live! (2017)   

                  genres  
8517  (no genres listed)  
8684  (no genres listed)  
8687  (no genres listed)  
8782  (no genres listed)  
8836  (no genres listed)  
8902  (no genres listed)  
9033  (no genres listed)  
9053  (no genres listed)  
9070  (no genres listed)  
9091  (no genres listed)  
9138  (no genres listed)  
9178  (no genres listed)  
9217  (no genres listed)  
9248  (no genres listed)  
9307  (no genres listed)  
9316  (no genres listed)  
9348  (no genres listed)  
9413  (no genres listed)  
9426  (no genres listed)  
9448  (no genres listed)  
9478  (no genres listed)  
9514  (no genres listed)  
9515  (no genres listed)  
9518  (no genres listed)  
9525  (no genres listed)  
9534  (no genres listed)  
9541  (no genres listed)  
9562  (no genres listed)  
9573  (no genres listed)  
9611  (no genres listed)  
9661  (no genres listed)  
9663  (no genres listed)  
9669  (no genres listed)

In [ ]:
#34개에서 33개로 줄어들었음을 알 수 있다.
len(refined_movies[no_genre_cond])

33

In [ ]:
no_genre_movieId = refined_movies.loc[no_genre_cond, 'movieId'].tolist()
len(no_genre_movieId)

33

In [ ]:
no_genre_movieId

[114335,
 122888,
 122896,
 129250,
 132084,
 134861,
 141131,
 141866,
 142456,
 143410,
 147250,
 149330,
 152037,
 155589,
 159161,
 159779,
 161008,
 165489,
 166024,
 167570,
 169034,
 171495,
 171631,
 171749,
 171891,
 172497,
 172591,
 173535,
 174403,
 176601,
 181413,
 181719,
 182727]

In [ ]:
refined_movies = refined_movies[~refined_movies['movieId'].isin(no_genre_movieId)].copy()
refined_movies

movieId                                      title  \
0           1                           Toy Story (1995)   
1           2                             Jumanji (1995)   
2           3                    Grumpier Old Men (1995)   
3           4                   Waiting to Exhale (1995)   
4           5         Father of the Bride Part II (1995)   
...       ...                                        ...   
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                                           genres  
0     Adventure|Animation|Children|Comedy|Fantasy  
1                      Adventure|Children|Fantasy  
2                                  Comedy|Romance  
3                            Comedy|Drama|Romance  
4                                          Comedy  
...                                           ...  
9737              Action|Animation|Comedy|Fantasy  
9738                     Animation|Comedy|Fantasy  
9739                                        Drama  
9740                             Action|Animation  
9741                                       Comedy  

[9704 rows x 3 columns]

In [ ]:
len(refined_ratings[refined_ratings['movieId'].isin(no_genre_movieId)])

46

In [ ]:
refined_ratings = refined_ratings[~refined_ratings['movieId'].isin(no_genre_movieId)].copy()
refined_ratings

userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100790 rows x 4 columns]

##영화 평점 결측치 해결

In [ ]:
duplicates = refined_ratings[refined_ratings.duplicated(['userId', 'movieId'], keep=False)]
print(duplicates)

       userId  movieId  rating   timestamp
4590       28    34048     3.5  1234516420
4747       28    34048     3.5  1234850075
11241      68    34048     2.0  1158532246
11451      68    34048     2.5  1230497715
17449     111     6003     4.0  1516468531
17819     111     6003     4.0  1517441257
80405     509      838     3.5  1436031723
80596     509      838     3.5  1436031753


전부 같은 평점임을 확인했으므로 timestamp 기준으로 먼저 진행한 평점 중복 삭제

In [ ]:
#중복된 행 4개 정리
refined_ratings = refined_ratings.drop(index=[4590, 11241, 17449, 80405])
len(refined_ratings)
#100790->100786으로 4개 삭제 확인

100786

movie와 rating merge = 평점 예측에 활용

In [ ]:
df = pd.merge(refined_ratings, refined_movies, on='movieId', how='left')
df = df.drop('genres', axis=1)
df

userId  movieId  rating   timestamp                           title
0            1        1     4.0   964982703                Toy Story (1995)
1            1        3     4.0   964981247         Grumpier Old Men (1995)
2            1        6     4.0   964982224                     Heat (1995)
3            1       47     5.0   964983815     Seven (a.k.a. Se7en) (1995)
4            1       50     5.0   964982931      Usual Suspects, The (1995)
...        ...      ...     ...         ...                             ...
100781     610   166534     4.0  1493848402                    Split (2017)
100782     610   168248     5.0  1493850091   John Wick: Chapter Two (2017)
100783     610   168250     5.0  1494273047                  Get Out (2017)
100784     610   168252     5.0  1493846352                    Logan (2017)
100785     610   170875     3.0  1493846415  The Fate of the Furious (2017)

[100786 rows x 5 columns]

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
# 사용자-아이템 행렬 생성
user_item_matrix = refined_ratings.pivot(index='userId', columns='movieId', values='rating')

user_item_matrix

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     NaN     4.0     NaN     NaN     4.0     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...     ...     ...     ...     ...     ...     ...   
606         2.5     NaN     NaN     NaN     NaN     NaN     2.5     NaN   
607         4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
608         2.5     2.0     2.0     NaN     NaN     NaN     NaN     NaN   
609         3.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
610         5.0     NaN     NaN     NaN     NaN     5.0     NaN     NaN   

movieId  9       10      ...  193565  193567  193571  193573  193579  193581  \
userId                   ...                                                   
1           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
606         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
607         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
608         NaN     4.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   
609         NaN     4.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   
610         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  193583  193585  193587  193609  
userId                                   
1           NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN  
...         ...     ...     ...     ...  
606         NaN     NaN     NaN     NaN  
607         NaN     NaN     NaN     NaN  
608         NaN     NaN     NaN     NaN  
609         NaN     NaN     NaN     NaN  
610         NaN     NaN     NaN     NaN  

[610 rows x 9686 columns]

결측치는 KNN으로 처리

In [ ]:
from sklearn.impute import KNNImputer

# KNNImputer 사용
imputer = KNNImputer(n_neighbors=5)
KNN_user_item_matrix = imputer.fit_transform(user_item_matrix)

KNN_user_item_df = pd.DataFrame(KNN_user_item_matrix, columns=user_item_matrix.columns, index=user_item_matrix.index)

KNN_user_item_df

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     3.6     4.0     2.8     3.4     4.0     3.2     3.0   
2           4.0     3.6     2.9     2.1     2.2     3.7     2.8     3.0   
3           3.7     3.0     2.1     2.7     2.8     3.3     2.5     2.8   
4           3.9     3.6     3.6     2.5     3.2     3.2     3.6     3.0   
5           4.0     3.4     3.3     2.1     2.6     4.0     3.2     2.6   
...         ...     ...     ...     ...     ...     ...     ...     ...   
606         2.5     3.6     3.3     2.7     2.8     3.8     2.5     2.4   
607         4.0     3.8     4.0     2.8     3.6     3.8     4.0     2.6   
608         2.5     2.0     2.0     2.1     2.9     4.3     3.2     2.8   
609         3.0     3.3     3.5     2.5     3.1     3.9     3.3     2.8   
610         5.0     3.4     3.2     2.5     3.2     5.0     3.5     2.4   

movieId  9       10      ...  193565  193567  193571  193573  193579  193581  \
userId                   ...                                                   
1           2.9     3.6  ...     3.5     3.0     4.0     4.0     3.5     4.0   
2           2.4     3.3  ...     3.5     3.0     4.0     4.0     3.5     4.0   
3           2.8     4.0  ...     3.5     3.0     4.0     4.0     3.5     4.0   
4           3.4     3.7  ...     3.5     3.0     4.0     4.0     3.5     4.0   
5           3.5     3.5  ...     3.5     3.0     4.0     4.0     3.5     4.0   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
606         2.6     3.9  ...     3.5     3.0     4.0     4.0     3.5     4.0   
607         3.3     3.9  ...     3.5     3.0     4.0     4.0     3.5     4.0   
608         2.6     4.0  ...     3.5     3.0     4.0     4.0     3.5     4.0   
609         2.5     4.0  ...     3.5     3.0     4.0     4.0     3.5     4.0   
610         3.0     3.4  ...     3.5     3.0     4.0     4.0     3.5     4.0   

movieId  193583  193585  193587  193609  
userId                                   
1           3.5     3.5     3.5     4.0  
2           3.5     3.5     3.5     4.0  
3           3.5     3.5     3.5     4.0  
4           3.5     3.5     3.5     4.0  
5           3.5     3.5     3.5     4.0  
...         ...     ...     ...     ...  
606         3.5     3.5     3.5     4.0  
607         3.5     3.5     3.5     4.0  
608         3.5     3.5     3.5     4.0  
609         3.5     3.5     3.5     4.0  
610         3.5     3.5     3.5     4.0  

[610 rows x 9686 columns]

In [ ]:
# 0.5미만이거나 5 초과인 userId, movieId, 점수 리스트 추출
filtered_ratings = KNN_user_item_df.unstack().reset_index()
filtered_ratings.columns = ['movieId', 'userId', 'rating']
filtered_ratings[(filtered_ratings['rating'] < 0.5) | (filtered_ratings['rating'] > 5)]

Empty DataFrame
Columns: [movieId, userId, rating]
Index: []

조건을 만족하는 영화가 없으므로 특정 점수를 조절할 필요가 없다.

만약 5초과 혹은 0.5미만의 점수가 있다면 범위안으로 들어오게 조절해줄 필요가 있다.

# Dot-Production 진행

평점 기록이 없는 영화도 선별

In [ ]:
# refined_movies의 movieId 목록
all_movie_ids = refined_movies['movieId'].unique()

# KNN_user_item_df의 movieId 목록
knn_movie_ids = KNN_user_item_df.columns

# refined_movies에 있는 movieId 중 KNN_user_item_df에 없는 movieId 찾기
missing_movie_ids = [movie_id for movie_id in all_movie_ids if movie_id not in knn_movie_ids]

missing_movie_ids

[1076,
 2939,
 3338,
 3456,
 4194,
 5721,
 6668,
 6849,
 7020,
 7792,
 8765,
 25855,
 26085,
 30892,
 32160,
 32371,
 34482,
 85565]

In [ ]:
#아직 아무도 보지 않은 영화
not_watched_movies = refined_movies[refined_movies['movieId'].isin(missing_movie_ids)]
not_watched_movies

movieId                                         title  \
816      1076                         Innocents, The (1961)   
2211     2939                                Niagara (1953)   
2499     3338                        For All Mankind (1989)   
2587     3456  Color of Paradise, The (Rang-e khoda) (1999)   
3118     4194                I Know Where I'm Going! (1945)   
4037     5721                            Chosen, The (1981)   
4506     6668   Road Home, The (Wo de fu qin mu qin) (1999)   
4598     6849                                Scrooge (1970)   
4704     7020                                  Proof (1991)   
5020     7792                     Parallax View, The (1974)   
5293     8765                      This Gun for Hire (1942)   
5421    25855                  Roaring Twenties, The (1939)   
5452    26085                   Mutiny on the Bounty (1962)   
5749    30892            In the Realms of the Unreal (2004)   
5824    32160                      Twentieth Century (1934)   
5837    32371                     Call Northside 777 (1948)   
5957    34482                  Browning Version, The (1951)   
7565    85565                            Chalet Girl (2011)   

                        genres  
816      Drama|Horror|Thriller  
2211            Drama|Thriller  
2499               Documentary  
2587                     Drama  
3118         Drama|Romance|War  
4037                     Drama  
4506             Drama|Romance  
4598     Drama|Fantasy|Musical  
4704      Comedy|Drama|Romance  
5020                  Thriller  
5293  Crime|Film-Noir|Thriller  
5421      Crime|Drama|Thriller  
5452   Adventure|Drama|Romance  
5749     Animation|Documentary  
5824                    Comedy  
5837     Crime|Drama|Film-Noir  
5957                     Drama  
7565            Comedy|Romance

In [ ]:
N_W_ID = not_watched_movies['movieId']
N_W_ID

816      1076
2211     2939
2499     3338
2587     3456
3118     4194
4037     5721
4506     6668
4598     6849
4704     7020
5020     7792
5293     8765
5421    25855
5452    26085
5749    30892
5824    32160
5837    32371
5957    34482
7565    85565
Name: movieId, dtype: int64

영화 X 장르 매트릭스

In [ ]:
# 장르를 '|'로 나누고 리스트로 변환
genres_list = refined_movies['genres'].str.split('|')

# 결과 확인
genres_list

0       [Adventure, Animation, Children, Comedy, Fantasy]
1                          [Adventure, Children, Fantasy]
2                                       [Comedy, Romance]
3                                [Comedy, Drama, Romance]
4                                                [Comedy]
                              ...                        
9737                 [Action, Animation, Comedy, Fantasy]
9738                         [Animation, Comedy, Fantasy]
9739                                              [Drama]
9740                                  [Action, Animation]
9741                                             [Comedy]
Name: genres, Length: 9704, dtype: object

In [ ]:
# 각 행의 장르 리스트를 하나의 큰 리스트로 모음
all_genres = [genre for genres_list in genres_list.dropna() for genre in genres_list]

# 중복 제거를 위해 set으로 변환 후 리스트로 다시 변환
unique_genres = list(set(all_genres))

# 결과 출력
print(unique_genres)

['Sci-Fi', 'Musical', 'Romance', 'Horror', 'Crime', 'Thriller', 'Adventure', 'Comedy', 'Film-Noir', 'Action', 'Mystery', 'Animation', 'Western', 'Fantasy', 'Documentary', 'War', 'IMAX', 'Children', 'Drama']


In [ ]:
# 결과를 담을 데이터프레임 생성
genres_matrix = pd.DataFrame(index=refined_movies['movieId'], columns=unique_genres)

# NaN 값을 0으로 채우기
genres_matrix = genres_matrix.fillna(0)

# 각 영화의 장르에 해당하는 열에 1을 할당
for idx, genres in enumerate(genres_list):
    genres_matrix.loc[refined_movies['movieId'].iloc[idx], genres] = 1

# 결과 확인
genres_matrix

Sci-Fi  Musical  Romance  Horror  Crime  Thriller  Adventure  Comedy  \
movieId                                                                         
1             0        0        0       0      0         0          1       1   
2             0        0        0       0      0         0          1       0   
3             0        0        1       0      0         0          0       1   
4             0        0        1       0      0         0          0       1   
5             0        0        0       0      0         0          0       1   
...         ...      ...      ...     ...    ...       ...        ...     ...   
193581        0        0        0       0      0         0          0       1   
193583        0        0        0       0      0         0          0       1   
193585        0        0        0       0      0         0          0       0   
193587        0        0        0       0      0         0          0       0   
193609        0        0        0       0      0         0          0       1   

         Film-Noir  Action  Mystery  Animation  Western  Fantasy  Documentary  \
movieId                                                                         
1                0       0        0          1        0        1            0   
2                0       0        0          0        0        1            0   
3                0       0        0          0        0        0            0   
4                0       0        0          0        0        0            0   
5                0       0        0          0        0        0            0   
...            ...     ...      ...        ...      ...      ...          ...   
193581           0       1        0          1        0        1            0   
193583           0       0        0          1        0        1            0   
193585           0       0        0          0        0        0            0   
193587           0       1        0          1        0        0            0   
193609           0       0        0          0        0        0            0   

         War  IMAX  Children  Drama  
movieId                              
1          0     0         1      0  
2          0     0         1      0  
3          0     0         0      0  
4          0     0         0      1  
5          0     0         0      0  
...      ...   ...       ...    ...  
193581     0     0         0      0  
193583     0     0         0      0  
193585     0     0         0      1  
193587     0     0         0      0  
193609     0     0         0      0  

[9704 rows x 19 columns]

평가가 없는 영화 18개 따로 놓기

In [ ]:
# 'movieId' 열을 다시 인덱스로 변환
genres_matrix_reset = genres_matrix.reset_index()

# N_W_ID에 해당하는 movieId를 가진 행들을 삭제
filtered_matrix = genres_matrix_reset[~genres_matrix_reset['movieId'].isin(N_W_ID)]

# 다시 'movieId' 열을 인덱스로 설정
genres_matrix = filtered_matrix.set_index('movieId')

genres_matrix

Sci-Fi  Musical  Romance  Horror  Crime  Thriller  Adventure  Comedy  \
movieId                                                                         
1             0        0        0       0      0         0          1       1   
2             0        0        0       0      0         0          1       0   
3             0        0        1       0      0         0          0       1   
4             0        0        1       0      0         0          0       1   
5             0        0        0       0      0         0          0       1   
...         ...      ...      ...     ...    ...       ...        ...     ...   
193581        0        0        0       0      0         0          0       1   
193583        0        0        0       0      0         0          0       1   
193585        0        0        0       0      0         0          0       0   
193587        0        0        0       0      0         0          0       0   
193609        0        0        0       0      0         0          0       1   

         Film-Noir  Action  Mystery  Animation  Western  Fantasy  Documentary  \
movieId                                                                         
1                0       0        0          1        0        1            0   
2                0       0        0          0        0        1            0   
3                0       0        0          0        0        0            0   
4                0       0        0          0        0        0            0   
5                0       0        0          0        0        0            0   
...            ...     ...      ...        ...      ...      ...          ...   
193581           0       1        0          1        0        1            0   
193583           0       0        0          1        0        1            0   
193585           0       0        0          0        0        0            0   
193587           0       1        0          1        0        0            0   
193609           0       0        0          0        0        0            0   

         War  IMAX  Children  Drama  
movieId                              
1          0     0         1      0  
2          0     0         1      0  
3          0     0         0      0  
4          0     0         0      1  
5          0     0         0      0  
...      ...   ...       ...    ...  
193581     0     0         0      0  
193583     0     0         0      0  
193585     0     0         0      1  
193587     0     0         0      0  
193609     0     0         0      0  

[9686 rows x 19 columns]

영화 X 영화 (장르 유사도) 매트릭스

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
movie_similarity = cosine_similarity(genres_matrix, genres_matrix)

In [ ]:
movie_similarity = pd.DataFrame(movie_similarity, index=genres_matrix.index, columns=genres_matrix.index)
movie_similarity

movieId    1         2         3         4         5         6         7       \
movieId                                                                         
1        1.000000  0.774597  0.316228  0.258199  0.447214  0.000000  0.316228   
2        0.774597  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
3        0.316228  0.000000  1.000000  0.816497  0.707107  0.000000  1.000000   
4        0.258199  0.000000  0.816497  1.000000  0.577350  0.000000  0.816497   
5        0.447214  0.000000  0.707107  0.577350  1.000000  0.000000  0.707107   
...           ...       ...       ...       ...       ...       ...       ...   
193581   0.670820  0.288675  0.353553  0.288675  0.500000  0.288675  0.353553   
193583   0.774597  0.333333  0.408248  0.333333  0.577350  0.000000  0.408248   
193585   0.000000  0.000000  0.000000  0.577350  0.000000  0.000000  0.000000   
193587   0.316228  0.000000  0.000000  0.000000  0.000000  0.408248  0.000000   
193609   0.447214  0.000000  0.707107  0.577350  1.000000  0.000000  0.707107   

movieId    8         9         10      ...    193565    193567    193571  \
movieId                                ...                                 
1        0.632456  0.000000  0.258199  ...  0.447214  0.316228  0.316228   
2        0.816497  0.000000  0.333333  ...  0.000000  0.000000  0.000000   
3        0.000000  0.000000  0.000000  ...  0.353553  0.000000  0.500000   
4        0.000000  0.000000  0.000000  ...  0.288675  0.408248  0.816497   
5        0.000000  0.000000  0.000000  ...  0.500000  0.000000  0.707107   
...           ...       ...       ...  ...       ...       ...       ...   
193581   0.000000  0.500000  0.288675  ...  0.750000  0.353553  0.353553   
193583   0.000000  0.000000  0.000000  ...  0.577350  0.408248  0.408248   
193585   0.000000  0.000000  0.000000  ...  0.000000  0.707107  0.707107   
193587   0.000000  0.707107  0.408248  ...  0.707107  0.500000  0.000000   
193609   0.000000  0.000000  0.000000  ...  0.500000  0.000000  0.707107   

movieId    193573  193579    193581    193583   193585    193587    193609  
movieId                                                                     
1        0.447214     0.0  0.670820  0.774597  0.00000  0.316228  0.447214  
2        0.000000     0.0  0.288675  0.333333  0.00000  0.000000  0.000000  
3        0.000000     0.0  0.353553  0.408248  0.00000  0.000000  0.707107  
4        0.000000     0.0  0.288675  0.333333  0.57735  0.000000  0.577350  
5        0.000000     0.0  0.500000  0.577350  0.00000  0.000000  1.000000  
...           ...     ...       ...       ...      ...       ...       ...  
193581   0.500000     0.0  1.000000  0.866025  0.00000  0.707107  0.500000  
193583   0.577350     0.0  0.866025  1.000000  0.00000  0.408248  0.577350  
193585   0.000000     0.0  0.000000  0.000000  1.00000  0.000000  0.000000  
193587   0.707107     0.0  0.707107  0.408248  0.00000  1.000000  0.000000  
193609   0.000000     0.0  0.500000  0.577350  0.00000  0.000000  1.000000  

[9686 rows x 9686 columns]

평점 예측

In [ ]:
def predict_ratings(similarity, ratings):
  #평점과 유사도의 곱을 계산
  ratings_dot_similarity = ratings.dot(similarity)

  #유사도의 합을 계산(0으로 나누느 것을 방지하기 위해 매우 작은 값을 더함)
  sum_similarity = ratings.apply(lambda x: x.replace(0, np.nan)).notna().dot(similarity).replace(0, np.nan) + 1e-10

  #평점 예측을 계산
  predicted_ratings = ratings_dot_similarity.div(sum_similarity)

  return predicted_ratings

predicted_ratings = predict_ratings(movie_similarity, KNN_user_item_df)

predicted_ratings

movieId    1         2         3         4         5         6         7       \
userId                                                                          
1        3.312518  3.343968  3.304520  3.399020  3.250424  3.283482  3.304520   
2        3.210237  3.205882  3.225639  3.326011  3.169135  3.187755  3.225639   
3        3.127659  3.117602  3.137044  3.239740  3.090321  3.116765  3.137044   
4        3.169538  3.140743  3.192716  3.290791  3.141519  3.103386  3.192716   
5        3.175493  3.162484  3.192821  3.302491  3.137461  3.131578  3.192821   
...           ...       ...       ...       ...       ...       ...       ...   
606      3.197445  3.178611  3.228966  3.337499  3.165782  3.167268  3.228966   
607      3.231297  3.230663  3.250330  3.354535  3.191569  3.216974  3.250330   
608      3.143022  3.132201  3.164904  3.286718  3.103655  3.191411  3.164904   
609      3.149092  3.121544  3.178882  3.281671  3.121656  3.114635  3.178882   
610      3.264660  3.269204  3.272325  3.371673  3.220985  3.252003  3.272325   

movieId    8         9         10      ...    193565    193567    193571  \
userId                                 ...                                 
1        3.342330  3.229054  3.277740  ...  3.272498  3.526787  3.390109   
2        3.195666  3.115077  3.166687  ...  3.179449  3.456277  3.316989   
3        3.103425  3.057110  3.099006  ...  3.108940  3.372402  3.235671   
4        3.127352  3.014096  3.075458  ...  3.123246  3.418424  3.283844   
5        3.150797  3.041660  3.105685  ...  3.133025  3.442974  3.295602   
...           ...       ...       ...  ...       ...       ...       ...   
606      3.163318  3.068390  3.138904  ...  3.161794  3.472998  3.326772   
607      3.217240  3.134769  3.195752  ...  3.195068  3.485475  3.345123   
608      3.116563  3.108158  3.160191  ...  3.133545  3.438662  3.279178   
609      3.110566  3.018543  3.085827  ...  3.112055  3.412233  3.272730   
610      3.257094  3.175327  3.231792  ...  3.234251  3.499861  3.364878   

movieId    193573    193579    193581    193583    193585    193587    193609  
userId                                                                         
1        3.662260  3.797509  3.285877  3.303288  3.511732  3.335105  3.250424  
2        3.551230  3.789577  3.191371  3.214749  3.445726  3.221850  3.169135  
3        3.463963  3.776950  3.116856  3.135162  3.362228  3.156710  3.090321  
4        3.514325  3.787446  3.143078  3.182599  3.407767  3.136555  3.141519  
5        3.530075  3.792882  3.149956  3.183139  3.433296  3.161227  3.137461  
...           ...       ...       ...       ...       ...       ...       ...  
606      3.527451  3.791641  3.175264  3.208011  3.466947  3.180771  3.165782  
607      3.545340  3.792733  3.211988  3.235649  3.478822  3.235279  3.191569  
608      3.498545  3.778968  3.141115  3.151214  3.432007  3.203727  3.103655  
609      3.483890  3.782391  3.127604  3.161021  3.404270  3.132463  3.121656  
610      3.587104  3.800090  3.245500  3.267002  3.490166  3.276132  3.220985  

[610 rows x 9686 columns]

예측 정확도 분석

In [ ]:
from sklearn.model_selection import train_test_split

_, test_data = train_test_split(df[['userId', 'movieId', 'rating']],
                test_size=20000, random_state=1234, stratify=df['userId'])
test_data

userId  movieId  rating
72020     464      367     2.5
90525     590      431     4.0
20357     135      551     4.0
42823     288     3869     4.0
37920     258   122918     3.5
...       ...      ...     ...
94955     599   122916     3.0
64569     414    51086     3.0
68836     448     1374     3.0
38368     263     5013     4.5
42378     288     1665     3.0

[20000 rows x 3 columns]

In [ ]:
df_pred_all = predicted_ratings.stack().reset_index()

df_pred_all.columns = ['userId', 'movieId', 'pred_rating']
df_pred_all

userId  movieId  pred_rating
0             1        1     3.312518
1             1        2     3.343968
2             1        3     3.304520
3             1        4     3.399020
4             1        5     3.250424
...         ...      ...          ...
5908455     610   193581     3.245500
5908456     610   193583     3.267002
5908457     610   193585     3.490166
5908458     610   193587     3.276132
5908459     610   193609     3.220985

[5908460 rows x 3 columns]

In [ ]:
test_data = pd.merge(test_data, df_pred_all, on=['userId', 'movieId'], how='left')
test_data

userId  movieId  rating  pred_rating
0         464      367     2.5     3.215809
1         590      431     4.0     3.397485
2         135      551     4.0     3.315094
3         288     3869     4.0     3.141160
4         258   122918     3.5     3.184578
...       ...      ...     ...          ...
19995     599   122916     3.0     2.912043
19996     414    51086     3.0     3.383887
19997     448     1374     3.0     3.026685
19998     263     5013     4.5     3.341196
19999     288     1665     3.0     3.141160

[20000 rows x 4 columns]

수치로 확인

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error


true_y = np.array(test_data['rating'])
pred_y = np.array(test_data['pred_rating'])

mae = mean_absolute_error(y_true=true_y, y_pred=pred_y)
mse = mean_squared_error(y_true=true_y, y_pred=pred_y)
rmse = np.sqrt(mse)

print(f"MAE  : {str(round(mae, 2))}")
print(f"MSE  : {str(round(mse, 2))}")
print(f"RMSE : {str(round(rmse, 2))}")

MAE  : 0.85
MSE  : 1.08
RMSE : 1.04


영화의 전체 평점 정리

In [ ]:
# user 120의 평점 추출
user_pred_ratings = predicted_ratings.loc[120, :]

user_pred_ratings

movieId
1         3.200362
2         3.194633
3         3.215096
4         3.321881
5         3.159813
            ...   
193581    3.177529
193583    3.205117
193585    3.449244
193587    3.199002
193609    3.159813
Name: 120, Length: 9686, dtype: float64

In [ ]:
# average_ratings을 데이터프레임으로 변환
user_pred_ratings = user_pred_ratings.reset_index(name='pred_rating')

user_pred_ratings

movieId  pred_rating
0           1     3.200362
1           2     3.194633
2           3     3.215096
3           4     3.321881
4           5     3.159813
...       ...          ...
9681   193581     3.177529
9682   193583     3.205117
9683   193585     3.449244
9684   193587     3.199002
9685   193609     3.159813

[9686 rows x 2 columns]

##최근 많이 본 영화 장르 추천


사용자 선택

In [ ]:
selected_user = 120

In [ ]:
selected_user_movie = refined_ratings[refined_ratings['userId'] == selected_user]
selected_user_movie

userId  movieId  rating  timestamp
18751     120        5     4.0  860070029
18752     120       12     3.0  860070182
18753     120       32     3.0  860069973
18754     120       52     3.0  860070065
18755     120      141     3.0  860069973
18756     120      260     5.0  860070065
18757     120      608     5.0  860070029
18758     120      631     3.0  860070216
18759     120      648     3.0  860069973
18760     120      653     3.0  860070065
18761     120      733     4.0  860070029
18762     120      736     3.0  860069973
18763     120      743     3.0  860070141
18764     120      765     3.0  860070306
18765     120      780     2.0  860069973
18766     120      783     3.0  860070141
18767     120      802     4.0  860070101
18768     120      852     2.0  860070141
18769     120      858     5.0  860070306
18770     120     1073     2.0  860070029
18771     120     1210     5.0  860070182
18772     120     1367     4.0  860070258

In [ ]:
len(selected_user_movie)

22

사용자가 가장 최근에 본 영화 10개까지 선택

In [ ]:
# timestamp를 기준으로 내림차순 정렬(가장 최근에 시청한 영화 구분)
selected_user_movie_recent = selected_user_movie.sort_values(by='timestamp', ascending=False)

# 상위 10개까지 선택
recently_watched_movies = selected_user_movie_recent.head(10)

recently_watched_movies

userId  movieId  rating  timestamp
18769     120      858     5.0  860070306
18764     120      765     3.0  860070306
18772     120     1367     4.0  860070258
18758     120      631     3.0  860070216
18771     120     1210     5.0  860070182
18752     120       12     3.0  860070182
18766     120      783     3.0  860070141
18768     120      852     2.0  860070141
18763     120      743     3.0  860070141
18767     120      802     4.0  860070101

In [ ]:
len(recently_watched_movies)

10

최근에 시청한 영화 10개의 movieId 추출

In [ ]:
# 해당 movieId들을 뽑아내기
selected_user_movieId = recently_watched_movies['movieId']

# genres_matrix에서 해당 movieId들의 장르 정보 가져오기
selected_user_movies_genres = genres_matrix.loc[selected_user_movieId]
selected_user_movies_genres

Sci-Fi  Musical  Romance  Horror  Crime  Thriller  Adventure  Comedy  \
movieId                                                                         
858           0        0        0       0      1         0          0       0   
765           0        0        0       0      0         0          0       1   
1367          0        0        0       0      0         0          1       1   
631           0        1        1       0      0         0          1       0   
1210          1        0        0       0      0         0          1       0   
12            0        0        0       1      0         0          0       1   
783           0        1        1       0      0         0          0       0   
852           0        0        1       0      0         0          0       1   
743           0        0        0       0      0         0          0       1   
802           0        0        1       0      0         0          0       0   

         Film-Noir  Action  Mystery  Animation  Western  Fantasy  Documentary  \
movieId                                                                         
858              0       0        0          0        0        0            0   
765              0       0        0          0        0        0            0   
1367             0       0        0          0        0        0            0   
631              0       0        0          1        0        1            0   
1210             0       1        0          0        0        0            0   
12               0       0        0          0        0        0            0   
783              0       0        0          1        0        0            0   
852              0       0        0          0        0        0            0   
743              0       0        0          0        0        0            0   
802              0       0        0          0        0        0            0   

         War  IMAX  Children  Drama  
movieId                              
858        0     0         0      1  
765        0     0         0      1  
1367       0     0         1      0  
631        0     0         1      0  
1210       0     0         0      0  
12         0     0         0      0  
783        0     0         1      1  
852        0     0         0      1  
743        0     0         0      0  
802        0     0         0      1

In [ ]:
# 각 열(장르)의 합 구하기
genres_sum_df = pd.DataFrame(selected_user_movies_genres.sum(axis=0), columns=['Genres_sum']).T

# 결과 출력
genres_sum_df

Sci-Fi  Musical  Romance  Horror  Crime  Thriller  Adventure  \
Genres_sum       1        2        4       1      1         0          3   

            Comedy  Film-Noir  Action  Mystery  Animation  Western  Fantasy  \
Genres_sum       5          0       1        0          2        0        1   

            Documentary  War  IMAX  Children  Drama  
Genres_sum            0    0     0         3      5

In [ ]:
# genres_sum_df를 넘파이 어레이로 변환
genres_sum_array = genres_sum_df.to_numpy().reshape(1, -1)

# genres_matrix의 각 행에 대해 코사인 유사도 계산
cosine_sim_matrix = cosine_similarity(genres_matrix, genres_sum_array)

# 결과를 데이터프레임으로 변환
cosine_sim_df = pd.DataFrame(cosine_sim_matrix, index=genres_matrix.index, columns=['Cosine_유사도'])

cosine_sim_df

Cosine_유사도
movieId            
1          0.635707
2          0.410347
3          0.646162
4          0.820695
5          0.507673
...             ...
193581     0.456906
193583     0.468968
193585     0.507673
193587     0.215387
193609     0.507673

[9686 rows x 1 columns]

In [ ]:
watched_movies_total_score = cosine_sim_df.loc[~cosine_sim_df.index.isin(missing_movie_ids)]

watched_movies_total_score

Cosine_유사도
movieId            
1          0.635707
2          0.410347
3          0.646162
4          0.820695
5          0.507673
...             ...
193581     0.456906
193583     0.468968
193585     0.507673
193587     0.215387
193609     0.507673

[9686 rows x 1 columns]

In [ ]:
# movieId를 기준으로 두 데이터프레임을 합치기
merged_df = pd.merge(watched_movies_total_score, user_pred_ratings, on='movieId')

# 'Cosine_유사도'와 'average_rating'를 곱한 값을 새로운 열로 추가
merged_df['total_score'] = merged_df['Cosine_유사도'] * merged_df['pred_rating']

# 필요한 열만 선택
watched_movies_total_score = merged_df[['movieId', 'total_score']]

watched_movies_total_score

movieId  total_score
0           1     2.034493
1           2     1.310909
2           3     2.077474
3           4     2.726249
4           5     1.604152
...       ...          ...
9681   193581     1.451831
9682   193583     1.503098
9683   193585     1.751089
9684   193587     0.689025
9685   193609     1.604152

[9686 rows x 2 columns]

In [ ]:
# watched_movies_total_score에서 selected_user_movie의 movieId와 같은 행을 제거
watched_movies_total_score = watched_movies_total_score[~watched_movies_total_score['movieId'].isin(selected_user_movie['movieId'])]

watched_movies_total_score

movieId  total_score
0           1     2.034493
1           2     1.310909
2           3     2.077474
3           4     2.726249
5           6     0.372336
...       ...          ...
9681   193581     1.451831
9682   193583     1.503098
9683   193585     1.751089
9684   193587     0.689025
9685   193609     1.604152

[9664 rows x 2 columns]

가장 점수가 높은 영화 5개 추천

In [ ]:
# total_score가 가장 큰 상위 5개의 행을 선택
top_5_movies = watched_movies_total_score.nlargest(5, 'total_score')

refined_movies[refined_movies['movieId'].isin(top_5_movies['movieId'])]

movieId                                            title  \
1390     1907                                     Mulan (1998)   
6230    46062                       High School Musical (2006)   
6819    61071  Sisterhood of the Traveling Pants 2, The (2008)   
8349   108540  Ernest & Célestine (Ernest et Célestine) (2012)   
8983   138702                                     Feast (2014)   

                                                 genres  
1390  Adventure|Animation|Children|Comedy|Drama|Musi...  
6230              Children|Comedy|Drama|Musical|Romance  
6819                     Adventure|Comedy|Drama|Romance  
8349  Adventure|Animation|Children|Comedy|Drama|Romance  
8983            Animation|Children|Comedy|Drama|Romance

아직 아무도 보지 않은 영화 중에서도 추천

In [ ]:
Non_Watched = genres_matrix_reset[genres_matrix_reset['movieId'].isin(N_W_ID)]
Non_Watched.set_index('movieId', inplace=True)
Non_Watched

IMAX  Sci-Fi  Comedy  Mystery  Crime  Fantasy  Adventure  \
movieId                                                             
1076        0       0       0        0      0        0          0   
2939        0       0       0        0      0        0          0   
3338        0       0       0        0      0        0          0   
3456        0       0       0        0      0        0          0   
4194        0       0       0        0      0        0          0   
5721        0       0       0        0      0        0          0   
6668        0       0       0        0      0        0          0   
6849        0       0       0        0      0        1          0   
7020        0       0       1        0      0        0          0   
7792        0       0       0        0      0        0          0   
8765        0       0       0        0      1        0          0   
25855       0       0       0        0      1        0          0   
26085       0       0       0        0      0        0          1   
30892       0       0       0        0      0        0          0   
32160       0       0       1        0      0        0          0   
32371       0       0       0        0      1        0          0   
34482       0       0       0        0      0        0          0   
85565       0       0       1        0      0        0          0   

         Documentary  Drama  Romance  Action  Horror  Thriller  Animation  \
movieId                                                                     
1076               0      1        0       0       1         1          0   
2939               0      1        0       0       0         1          0   
3338               1      0        0       0       0         0          0   
3456               0      1        0       0       0         0          0   
4194               0      1        1       0       0         0          0   
5721               0      1        0       0       0         0          0   
6668               0      1        1       0       0         0          0   
6849               0      1        0       0       0         0          0   
7020               0      1        1       0       0         0          0   
7792               0      0        0       0       0         1          0   
8765               0      0        0       0       0         1          0   
25855              0      1        0       0       0         1          0   
26085              0      1        1       0       0         0          0   
30892              1      0        0       0       0         0          1   
32160              0      0        0       0       0         0          0   
32371              0      1        0       0       0         0          0   
34482              0      1        0       0       0         0          0   
85565              0      0        1       0       0         0          0   

         Western  Film-Noir  Children  Musical  War  
movieId                                              
1076           0          0         0        0    0  
2939           0          0         0        0    0  
3338           0          0         0        0    0  
3456           0          0         0        0    0  
4194           0          0         0        0    1  
5721           0          0         0        0    0  
6668           0          0         0        0    0  
6849           0          0         0        1    0  
7020           0          0         0        0    0  
7792           0          0         0        0    0  
8765           0          1         0        0    0  
25855          0          0         0        0    0  
26085          0          0         0        0    0  
30892          0          0         0        0    0  
32160          0          0         0        0    0  
32371          0          1         0        0    0  
34482          0          0         0        0    0  
85565          0          0         0        0    0

In [ ]:
# Non_Watched의 각 행에 대해 코사인 유사도 계산
Non_Watched_cosine_sim_matrix = cosine_similarity(Non_Watched, genres_sum_array)

# 결과를 데이터프레임으로 변환\
non_watched_movies_total_score = pd.DataFrame(Non_Watched_cosine_sim_matrix, index=Non_Watched.index, columns=['Cosine_유사도'])

non_watched_movies_total_score

Cosine_유사도
movieId            
1076       0.351726
2939       0.358979
3338       0.000000
3456       0.507673
4194       0.527589
5721       0.507673
6668       0.646162
6849       0.468968
7020       0.820695
7792       0.000000
8765       0.058621
25855      0.351726
26085      0.703452
30892      0.143592
32160      0.507673
32371      0.351726
34482      0.507673
85565      0.646162

코사인 유사도가 0.75 이상인 영화만 추천(가장 질 높은 추천을 위해서)

In [ ]:
top_5_cosine_similar_movies = non_watched_movies_total_score.nlargest(5, 'Cosine_유사도')
top_5_cosine_similar_movies = top_5_cosine_similar_movies[top_5_cosine_similar_movies['Cosine_유사도'] >= 0.75]
top_5_cosine_similar_movies

Cosine_유사도
movieId            
7020       0.820695

In [ ]:
similar_movie_ids = top_5_cosine_similar_movies.index.tolist()
similar_movie_ids

[7020]

In [ ]:
refined_movies[refined_movies['movieId'].isin(similar_movie_ids)]

movieId         title                genres
4704     7020  Proof (1991)  Comedy|Drama|Romance